### ISSUE TITLE
ClientError: /speechkit.tts.v3.Synthesizer/UtteranceSynthesis UNIMPLEMENTED

### ISSUE THREAD

**Issue by OnkelTem** [yandex-cloud/nodejs-sdk#122]
My code is as following:

```ts
import { Session, serviceClients } from '@yandex-cloud/nodejs-sdk';
import { UtteranceSynthesisRequest } from '@yandex-cloud/nodejs-sdk/dist/generated/yandex/cloud/ai/tts/v3/tts';

const YANDEX_IAM_TOKEN = '...'

export async function tts() {
  const session = new Session({ iamToken: YANDEX_IAM_TOKEN });
  const client = session.client(serviceClients.SynthesizerClient);
  const req = UtteranceSynthesisRequest.fromPartial({
    text: 'Hello, world!',
  });
  for await (let item of client.utteranceSynthesis(req)) {
    console.log(item);
  }
}
```

However, it raises an exception:

```
ClientError: /speechkit.tts.v3.Synthesizer/UtteranceSynthesis UNIMPLEMENTED: 
    at wrapClientError (node_modules/nice-grpc/src/client/wrapClientError.ts:7:12)
    at Object.serverStreamingMethod [as next] (node_modules/nice-grpc/src/client/createServerStreamingMethod.ts:80:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

What I do wrong?

**Comment by nikolaymatrosov** [comment]
There is an error in https://github.com/yandex-cloud/nodejs-sdk/blob/master/src/service-endpoints.ts#L260. Text to speech service should have separate endpoint defined. The right address is `tts.api.cloud.yandex.net:443`.

As a workaround you can override the endpoint in your code.

**Comment by OnkelTem** [comment]
Oh, thanks! I'll try that and write back.

**Comment by OnkelTem** [comment]
Wait, it's not a generated code, so maybe it's worth submitting a PR instead?
