### ISSUE TITLE
Проблема с созданием instance

### ISSUE THREAD

**Issue by ichirkin** [yandex-cloud/nodejs-sdk#13]
Делаю по примеру

```
const operation = await instanceService.create({
      folderId,
      zoneId: TARGET_ZONE_ID,
      platformId: 'standard-v2',
      resourcesSpec: {
        memory: Long.fromNumber(2 * 1024 * 1024 * 1024),
        cores: Long.fromNumber(2),
      },
      bootDiskSpec: {
        autoDelete: true,
        diskSpec: {
          size: Long.fromNumber(10 * 1024 * 1024 * 1024),
          imageId: image.id,
        },
      },
      networkInterfaceSpecs: [
        {
          subnetId: subNetwork.id,
          primaryV4AddressSpec: {
            oneToOneNatSpec: {ipVersion: IpVersion.IPV4},
          },
        },
      ],
    });
```
получаю эксепшен
```
Response deserialization failed: Cannot read property 'google' of undefined
(node:37183) UnhandledPromiseRejectionWarning: Error: 13 INTERNAL: Failed to parse server response
    at Object.exports.createStatusError (/Users/ivan/projects/aggregion/enclave-service-ts/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/ivan/projects/aggregion/enclave-service-ts/node_modules/grpc/src/client_interceptors.js:1213:28)
    at InterceptingListener._callNext (/Users/ivan/projects/aggregion/enclave-service-ts/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/ivan/projects/aggregion/enclave-service-ts/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/ivan/projects/aggregion/enclave-service-ts/node_modules/grpc/src/client_interceptors.js:849:24)
(node:37183) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:37183) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Через консоль видно, что ВМ создается

**Comment by vermilion** [comment]
Тоже столкнулся с данной проблемой, решилось импортом всей либы.
В contrib.google импортится в utils.js, а utils объявлен в index

```js
import * as cloud from "yandex-cloud";
import { InstanceService } from "yandex-cloud/api/compute/v1";

...
const session = new cloud.Session({ oauthToken: inputs.token });
var instanceService = new InstanceService(session);
```
