### ISSUE TITLE
Error: yandex.cloud.iot.broker.v1.BrokerDataService/Publish UNIMPLEMENTED

### ISSUE THREAD

**Issue by 1xtr** [yandex-cloud/nodejs-sdk#136]
Проблема при отправке сообщения в топик.

```js
import { cloudApi, serviceClients, Session } from '@yandex-cloud/nodejs-sdk'
import { getEnv } from './getEnv'
import { logger } from './logger'

const session = new Session({ iamToken: getEnv('TEMP_YC_TOKEN') })

const iotService = session.client(serviceClients.BrokerDataServiceClient)

const DB_CLUSTER_ID = getEnv('DB_CLUSTER_ID')

const brokerId = getEnv('TRIGGERS_BROKER_ID')
const topic = getEnv('DB_ENTITY_CREATED_TOPIC_NAME')

export const publishMessage = async (subdomain) => {
  try {
    const req = cloudApi.iot.broker_broker_data_service.PublishBrokerDataRequest.fromJSON({
      brokerId,
      topic,
      data: subdomain,
    })
    await iotService.publish(req)
    logger.info('Message published for $s', subdomain)
  } catch (error) {
    logger.error(error.message, error)
  }
}
```

Error:

```json5
{
  code: 12,
  details: '',
  level: 'error',
  message:
    '/yandex.cloud.iot.broker.v1.BrokerDataService/Publish UNIMPLEMENTED:  /yandex.cloud.iot.broker.v1.BrokerDataService/Publish UNIMPLEMENTED: ',
  path: '/yandex.cloud.iot.broker.v1.BrokerDataService/Publish',
  stack:
    'ClientError: /yandex.cloud.iot.broker.v1.BrokerDataService/Publish UNIMPLEMENTED: 
    at wrapClientError (D:\\project\\node_modules\\nice-grpc\\src\\client\\wrapClientError.ts:7:12)
    at Object.callback (D:\\project\\node_modules\\nice-grpc\\src\\client\\createUnaryMethod.ts:64:35)
    at Object.onReceiveStatus (D:\\project\\node_modules\\@grpc\\grpc-js\\src\\client.ts:356:26)
    at Object.onReceiveStatus (D:\\project\\node_modules\\@grpc\\grpc-js\\src\\client-interceptors.ts:455:34)
    at Object.onReceiveStatus (D:\\project\\node_modules\\@grpc\\grpc-js\\src\\client-interceptors.ts:417:48)
    at D:\\project\\node_modules\\@grpc\\grpc-js\\src\\resolving-call.ts:111:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)',
}
```

Ранее была проблема с отправкой через API, проблема решилась заменой endpoint'a на 
`iot-data.api.cloud.yandex.net`
вместо
`iot-broker.api.cloud.yandex.net`

**Comment by 1xtr** [comment]
Замена endpoint на `iot-broker.api.cloud.yandex.net:443` помогает.
Ждем фикс.

**Comment by nikolaymatrosov** [comment]
Я запутался. Как все таки правильно? Где и на что вы меняете?

**Comment by 1xtr** [comment]
Прошу прощения, сам тоже уже загнался ))
Исправил
